### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by mattcen** [govhackaustralia/hackerspace3#104]
See https://www.gizmodo.com.au/2020/06/github-to-remove-master-and-slave-coding-terms-widely-seen-as-racially-insensitive/ for rationale.

This *should* be an easy change (I've just made it to my own fork):

1. `git push origin master:main`
2. At https://github.com/govhackaustralia/hackerspace3/settings/branches, update Default branch to `main`
3. `git push origin :master`

I just didn't want to go ahead and make it without warning because it'll affect anyone who's got a check-out of the `master` branch (say, I dunno, in production! 😛 )

**Comment by cassar** [comment]
Yeah go ahead, better sooner rather than later before too many people start cloning the repo.

**Comment by cassar** [comment]
Another candidate that came up when we discussed this at work was 'canon' 😆

**Comment by mattcen** [comment]
All done! I went with 'main' because it seems to be one of the predominant choices. "Canon" might be a little obscure to some people :)
