### ISSUE TITLE
Registration page 3 (About You)

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#118]
Would be good to use semantic elements through out.
<img width="216" alt="Screen Shot 2020-07-13 at 11 06 54 pm" src="https://user-images.githubusercontent.com/4644609/87307825-99baad80-c55d-11ea-8f99-6a44ef2ed12c.png">

**Comment by ooliviarr** [comment]
Assigned to Luke to connect up to backend
