### ISSUE TITLE
Uniq team identifiers for AWS credits

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#160]
## Background

Teams require a uniq team identifier to apply for AWS credits.

## Tasks

- [ ] Incorporate the Team id into the team page somewhere.

Note: Team.id must be used as Project.id changes when A new project version is made.

**Comment by karwalski** [comment]
As the team pages appear to have been lowered in priority, I believe an alternate solution for AWS (and anyone else who wants to verify record teams externally) would be to use the project URL. Asking the teams to share their project URL which can resolved with a HTTP 200 without any authentication or HTTP 500 if the project URL is incorrect (maybe a bug there that it doesn't give a 404).

Example project URL https://hackerspace.govhack.org/projects/team_project_name

For AWS to verify they can either create a script or manually check. I plan on similar method for zoom room distribution

if URL response state = 500
   ask for correct project url, and hackerspace instructions/link
else if URL response state = 200
   split URL string and store last segment after lash forward slash

Making some assumptions, but this would likely meet the original requirement of AWS and doesn't need any code change. It allows them to verify teams without any authentication.. a unique team ID would be arbitrary to them if they have no way of validating it.. or potentially cause manual strain on GH to verify.

**Comment by cassar** [comment]
I'm assuming we got by fine without this? Closing for now.
