### ISSUE TITLE
Update Treasure Hunt page with finalised instructions & background image

### ISSUE THREAD

**Issue by ooliviarr** [govhackaustralia/hackerspace3#174]
![notebook](https://user-images.githubusercontent.com/2588619/89709236-7ef32180-d9c1-11ea-9027-09de4d7a478b.jpg)
Finalised instructions:

**Instructions:**

Getting lost can sometimes be the easiest way to discover new things. The GovHack Treasure Hunt will help you find your way around the digital competition.

Five correct answers will earn you a Treasure Hunt badge for your GovHack profile.

**How To Play:**

1. Each clue will lead you to a website or dataset
2. Search the website or dataset to look up the answer to the clue
3. Each answer will be a single non-case sensitive word or a number in numerical format e.g. 19585  

Note: you do **not** need to download files, register, or sign into any additional pages to find the answers.

![image](https://user-images.githubusercontent.com/2588619/89709036-83b6d600-d9bf-11ea-966a-ed41e7dda5bc.png)

**Comment by varunnaik** [comment]
@ooliviarr While this image looks great, it's aspect ratio is not suitable for this page, it leaves a gap to the right - see screenshot. 

Too much of this layout is fragile and I am not confident it can work everywhere. Unfortunately the text needs to be positioned according to the background image and the position of the book on all resolutions and monitors cannot be known reliably. After some analysis and considering the options, I have some suggestions.

The way I see it there are three possibilities:
1. Retain the old layout - this is still unreliable but works better than this new proposed layout (in the screenshot)
2. If you can split the background into two images - a book and the clipart background with no book and in a much larger size - this would be ideal. This way I can have the book as the background for the text and it may move to different positions on the background on different monitors.
3. Alternatively, if you can obtain a larger version of this image (book retains its current position but the background extends further to the right) I can attempt to make it work with a 1-column layout (i.e., text only on the left page and right page blank, or vice versa).



![image](https://user-images.githubusercontent.com/916835/89729774-71bd4d80-da28-11ea-8d58-68e29a7f817b.png)

**Comment by ooliviarr** [comment]
Hi @varunnaik thanks for putting together those options so clearly. I am now having option #2 done and will add the two images here once done. Thank you!

In terms of the clues, we'll be having 5 clues in total - each will be up to 270 characters (with spaces)

**Comment by ooliviarr** [comment]
Notebook only attached. Background image coming.

![notebook_only](https://user-images.githubusercontent.com/2588619/89752621-7fea9700-db18-11ea-9626-32071589c268.png)

**Comment by ooliviarr** [comment]
Background!
![large_background](https://user-images.githubusercontent.com/2588619/89775917-20a67a00-db4c-11ea-8336-28f151979e2e.png)

**Comment by varunnaik** [comment]
PR: https://github.com/govhackaustralia/hackerspace3/pull/176
