### ISSUE TITLE
Challenges for Competition : Missing Field in CSV

### ISSUE THREAD

**Issue by thedhanawada** [govhackaustralia/hackerspace3#194]
The [Challenges](https://hackerspace.govhack.org/challenges/table) downloaded as [CSV](https://hackerspace.govhack.org/challenges/table.csv) has a missing entries field. 

This field gives a view on the number of participating teams registered for a particular challenge. Since this field is listed under the table view and not in the downloadable CSV, I assume this was missed.

<img width="795" alt="Screen Shot 2020-08-16 at 5 51 50 am" src="https://user-images.githubusercontent.com/13751641/90320417-96637900-df84-11ea-9fad-ba88ce8ce2ca.png">

**Comment by cassar** [comment]
Hey @thedhanawada , thanks very much for reporting this, fixed now 👍
