### ISSUE TITLE
In Memory Testing

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#218]
## Background

Copied from Matt's comment below:

Just in case it helps, the functional requirement is to be about to set up a working hackerspace instance (at least, insofar is required to run unit regress tests) from nothing but the source code from git.

Technically, this means being dropped onto a clean Ubuntu environment with some basic tools preinstalled, cloning the GitHub repo, doing a bundle install, and then saying "run unit tests and exit non-zero on failure".
I think the best option for this last bit is having a rails environment that sets up an in-memory sqlite3 db, such that this environment's settings won't interfere with any other deployments, but am open to better ideas.

**Comment by mattcen** [comment]
Just in case it helps, the functional requirement is to be about to set up a working hackerspace instance (at least, insofar is required to run unit regress tests) from nothing but the source code from git.

Technically, this means being dropped onto a clean Ubuntu environment with some basic tools preinstalled, cloning the GitHub repo, doing a bundle install, and then saying "run unit tests and exit non-zero on failure".
 I *think* the best option for this last bit is having a rails environment that sets up an in-memory sqlite3 db, such that this environment's settings won't interfere with any other deployments, but am open to better ideas.

**Comment by cassar** [comment]
Have update this issue, as doing a bit of research seems to suggest that a new environment might not be the way to go.

Perhaps a flag that specifies which DB config to use when `$ rails test` is run.
