### ISSUE TITLE
Create New Slack Hackerspace App

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#232]
# Background

We need to create a slack app to integrate with the Hackerspace.

# Tasks

- [x] Create the app on the GovHack Slack API page.

**Comment by karwalski** [comment]
Created app - @GovHack Hackerspace
https://govhackhq.slack.com/services/B01P6UUBQJY

Shared OAuth access tokens with @cassar.

Provided the below scopes for profile integration, and potential bot messaging functionality. We can review and add/remove permissions as needed.

**User Token Scopes** Scopes that access user data and act on behalf of users that authorize them.

identify - View information about a user’s identity

users.profile:write - Edit a user’s profile information and status

**Bot Token Scopes** Scopes that govern what your app can access.

channels:read - View basic information about public channels in a workspace

chat:write - Send messages as @govhack_hackerspace

commands - Add shortcuts and/or slash commands that people can use

im:history - View messages and other content in direct messages that GovHack Hackerspace has been added to

im:write - Start direct messages with people

incoming-webhook - Post messages to specific channels in Slack (#hackerspace-help currently configured)
