### ISSUE TITLE
Agreement to Asset Upload

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#295]
## Background

Currently there is not agreement/consent before uploading an asset like an image or a document.

## Tasks

- [ ] Add a checkbox that needs to be checked before an asset is uploaded.
- [ ] Profile
- [ ] Challenge
- [ ] Projects

# Copy

[To be provided by @Cruion @ooliviarr ]

**Comment by ooliviarr** [comment]
## Copy to use:

This image belongs to:

- [ ] Me, and I am happy for GovHack to use it under a [CC BY-NC-SA licence](https://creativecommons.org/licenses/)
- [ ] Someone else

## If 'Me, and I am happy for GovHack to use it under a [CC BY-NC-SA licence](https://creativecommons.org/licenses/)' is selected:

Set the title image text as:

By `hackerspaceUsername`, licensed under [CC BY-NC-SA](https://creativecommons.org/licenses/)

Example:

By David J, licensed under [CC BY-NC-SA](https://creativecommons.org/licenses/)

## If 'Someone else' is selected:

Show an additional 4 fields with helper text:

- Title: Title of the image
- Author: Name of the creator
- Source: URL where the image is hosted
- Licence: The type of Creative Commons licence it is available under (https://creativecommons.org/licenses/)

The title image text should be formatted as:

"[Title](https://www.flickr.com/photos/sebilden/40512726042/)”, by Author, licensed under [Licence](https://creativecommons.org/licenses/)

Where the `title` links to the `source`

Example:

"[Winter in town](https://www.flickr.com/photos/sebilden/40512726042/)”, by [David J](https://www.flickr.com/photos/sebilden/), licensed under [CC BY 2.0](https://creativecommons.org/licenses/)

### Reference
- https://www.pixsy.com/academy/image-user/correctly-attribute-images/

**Comment by cassar** [comment]
@ooliviarr, what's outlined above is great but is *a lot* more work than originally requested.

The original idea was just that we show a check box with copy like, "tick to confirm that this image complies with GovHack copyright rules", and then we wouldn't let people upload till they had agreed. We weren't even going to store their acceptance. 😬

**Comment by ooliviarr** [comment]
> @ooliviarr, what's outlined above is great but is _a lot_ more work than originally requested.
> 
> The original idea was just that we show a check box with copy like, "tick to confirm that this image complies with GovHack copyright rules", and then we wouldn't let people upload till they had agreed. We weren't even going to store their acceptance. 😬

LOL all good! For another year. Have provided some wording on the PR
