### ISSUE TITLE
UI Refresh - Footer

### ISSUE THREAD

**Issue by rosieprom** [govhackaustralia/hackerspace3#339]
Acceptance Criteria
- Footer must have the Github link, Terms of Use, Privacy Policy and Copyright/small text

**Comment by cassar** [comment]
This is what we have already,

![Screen Shot 2022-06-27 at 5 57 54 pm](https://user-images.githubusercontent.com/4644609/175889555-4892da17-242e-43d1-a6d2-8d7bc51b0e63.png)

**Comment by ooliviarr** [comment]
Progress:
- [ ] Github link
- [ ] Terms of Use
- [ ] Privacy Policy
- [ ] Copyright/small text

**Comment by ooliviarr** [comment]
Privacy policy - https://govhack.org/privacy-statement-and-disclaimer/
