### ISSUE TITLE
SPIKE - Find new (copyright-free) image for login/signup pages

### ISSUE THREAD

**Issue by rosieprom** [govhackaustralia/hackerspace3#345]
- To find an image that we have rights to use
- Even better: create an album of images that we can use

**Comment by bmpickford** [comment]
URLs for a potential album based on what we have in WP, tried to get a bit of range with colours. There are a few more we can pull down but hopefully this is enough. Feel free to just pick one that looks nice on the login/signup page. Might need to crop whatever one we pick

https://govhack.org/wp-content/uploads/2022/06/road-trip-with-raj-J61Sh5YrQho-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/kishan-modi-UJR6GY2qtW4-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/davide-dalfovo-1rQs3661lq4-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/lode-lagrainge-oAYs_Jr1RnQ-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/dan-freeman-hIKVSVKH7No-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/tobias-keller-73F4pKoUkM0-unsplash.jpg
https://govhack.org/wp-content/uploads/2022/06/trevor-mckinnon-XfjmDeR7P7E-unsplash-1.jpg
https://govhack.org/wp-content/uploads/2022/06/spencer-chow-LdvSgcne6kM-unsplash-1.jpg
https://govhack.org/wp-content/uploads/2022/06/tobias-keller-gF0IZVVKrD0-unsplash.jpg

**Comment by MunyaradziMagura** [comment]
[signin-up images.zip](https://github.com/govhackaustralia/hackerspace3/files/11403813/signin-up.images.zip)

Files within in 

**Vertical Images** 
https://pixabay.com/photos/bokeh-lights-wet-gutter-2592859/
https://pixabay.com/photos/asia-rain-street-illumination-3713473/
https://pixabay.com/photos/city-metropolitan-sunset-building-4119806/
https://pixabay.com/photos/buildings-traffic-street-cars-5303864/
https://pixabay.com/photos/harbour-bridge-bridge-sydney-night-221509/
https://pixabay.com/photos/building-sydney-sky-clouds-4912040/
https://pixabay.com/photos/sydney-tower-sydney-architecture-164223/

**Horizontal images**
https://pixabay.com/photos/sydney-opera-house-building-363244/
https://pixabay.com/photos/cityscape-illuminated-313216/
https://pixabay.com/photos/sydney-opera-house-sydney-354375/
https://pixabay.com/photos/fireworks-harbour-night-celebration-4021214/
https://pixabay.com/photos/sydney-skyline-tower-sunset-4034244/
https://pixabay.com/photos/sydney-australia-panorama-night-1970604/
https://pixabay.com/photos/buildings-skyscrapers-7945163/
https://pixabay.com/photos/building-skyline-cityline-spanda-7945135/
https://pixabay.com/photos/melbourne-city-cityscape-tower-sky-2262238/
https://pixabay.com/photos/panoramic-landscape-clouds-rain-949448/
https://pixabay.com/photos/melbourne-night-shot-station-city-966467/
https://pixabay.com/photos/skyline-dusk-melbourne-cbd-1337971/
https://pixabay.com/photos/light-city-mountains-night-1284441/
