### ISSUE TITLE
UI Refresh - Login to Hackerspace

### ISSUE THREAD

**Issue by rosieprom** [govhackaustralia/hackerspace3#346]
### Acceptance Criteria 
- Design to reflect a side image

### Links
Figma: https://www.figma.com/file/omAtzW5Kfg7NN97ECuQ3GC/Govhack-Hackerspace-Reskin?node-id=1080-948&t=hXhXKM8946xe3Atq-0

**Comment by bmpickford** [comment]
Link has been done, just needs the side image updated

**Comment by bmpickford** [comment]
I believe login has been done, but signup needs the image too
