### ISSUE TITLE
UI Refresh - Side Menu - Challenges

### ISSUE THREAD

**Issue by rosieprom** [govhackaustralia/hackerspace3#347]
### Acceptance Criteria
- Should allow filtering by State Eligibility
- Should allow search by key words
- Should allow filtering by Theme/Topic (Skip this for now)

### Links
Figma: https://www.figma.com/file/omAtzW5Kfg7NN97ECuQ3GC/Govhack-Hackerspace-Reskin?node-id=745-544&t=hXhXKM8946xe3Atq-0

### Location:
1. Go to Challenges
2. Click a Challenge
Sample link: https://staging.hackerspace.govhack.org/regions/international_2023

**Comment by PegliOne** [comment]
The new side menu has been added.
