### ISSUE TITLE
Register for Event - Add "Organisational Identifier" - Optional field

### ISSUE THREAD

**Issue by rosieprom** [govhackaustralia/hackerspace3#355]
## Background

From Jason: To be used by event hosts to check to make sure that folks registered for the event are meant to be attending that event, and otherwise if not meant to be there encourage them to change to another venue.
An example is: We are going to have two venues in Victoria that will be open to used employees or students of the venue. Want the people registering for it to record an organisational identifier such as student id or work email (if created account with different email).
One of the events may open to others if the primary event reaches capacity but still want to record if folks are affiliated with the venue

**Acceptance Criteria**
- An optional field for competitors and attendees to enter their Student ID/Email Address 
- Open Text field
- For event pages

**Comment by ooliviarr** [comment]
I've checked with Jason and for this first iteration given we have other tickets:

- Just display an optional text field for all events
- Label the text field 'Organisational ID for this event e.g. student ID, work email'
- We will ask organisers to specify in the event description what should be entered into the Organisational ID field
- It will be the organiser's responsibility to review what each event registrant puts into that field and reach out if necessary

**Comment by 00Chaotic** [comment]
Due to some uncertainty around the purpose and implementation of this piece of work, the decision has been made to postpone it for now.

**Comment by cassar** [comment]
Closing, can reopen if we find we need it.
