### ISSUE TITLE
Mentor Eol Link in New Registration Form Out of Date

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#48]
## Background

The link in the below mark down in file `app/views/registrations/_user_model_attrs.html.haml` appears to be out of date.

This portion of the view has been commented out for now.

```
  %strong Want to be a Mentor?
  = succeed "Head" do
    %br/
    %a{href: 'http://govhack.org/mentor', target: '_blank'} Mentor EoI
    to express your interest and we will be in contact with you shortly. No need to register here.
```

## Tasks  

- [x] Update the form stack link for this year.
- [x] Uncomment the code.

**Comment by Cruion** [comment]
Have updated where the mentor url points to.

**Comment by cassar** [comment]
All righty, will uncomment the code.
