### ISSUE TITLE
Allow download of teams that includes location

### ISSUE THREAD

**Issue by mattcen** [govhackaustralia/hackerspace3#68]
Currently there's no machine-readable way to download team data that includes their location. This data can be copied/pasted from https://hackerspace.govhack.org/admin/competitions/2/teams, but that's not ideal.

Please make this available as a CSV export.

**Comment by cassar** [comment]
Hey @mattcen , added to "team member" and "team entry" csvs.

**Comment by mattcen** [comment]
Thanks, @cassar!
