### ISSUE TITLE
NoMethodError: undefined method `holder_for' for nil:NilClass

### ISSUE THREAD

**Issue by 1ce8erg0** [govhackaustralia/hackerspace3#84]
Hi, 
I have the following error with db:setup on localhost.  All pass in rails test. 

   NoMethodError: undefined method `holder_for' for nil:NilClass

export SEED_EMAIL = 'foo_bar@localhost.com'
export SEED_NAME = 'foo bar'
export STAGE='PRE_CONNECTION'

pg (1.2.3)
Rails 6.0.2.2
ruby 2.6.5p114

**Comment by cassar** [comment]
Hey Jimmy,

"All pass in rails test.", tells me the app is probably hooked up to the database ok, 

First thing I'd check is if the 'SEED_EMAIL' is actually set.

"NoMethodError: undefined method `holder_for' for nil:NilClass", means that the user wasn't saved.

Looks like you might be using direnv? 

Try `$ direnv allow` to set the variables.

And then try running the below to check that the variable was set...

```shell
$ rails c
```
```ruby
Loading development environment (Rails 6.0.2.2)
irb(main):001:0> ENV['SEED_EMAIL']
```

Other than that, put a bang (!) after "email" on `db/seeders/user_seeder.rb:22`, like so
```ruby
user = User.find_by_email!(ENV['SEED_EMAIL'])
```

This may give you more information next time you run it. 🤞

**Comment by 1ce8erg0** [comment]
Thank you.  I pasted the seed `[Rails.application.load_seed]` output  here. 

https://pastebin.com/RmscznSY

I can finish db:setup and login with my seed_user If I comment out **'RegionSeeder.create comp'** in competition_seeder.rb. The error in my case hit  this line : 

```ruby
  def assign_leader(user)
->     leader_assignments.create user: user, holder: user.holder_for(competition)
  end
```
which in Team_seeder.rb - I got a null in finding assignment_id and user_id   
	`assignment_ids = Registration.where(event: events).pluck `:assignment_id

I wonder if I miss something else. Cheers

**Comment by cassar** [comment]
Hey Jimmy,

I have pushed some changes to master, you won't have to set the 'SEED_EMAIL' or 'SEED_NAME' to run the script (not that that was your problem), and have added some guard classes so the script will exit a section if there happens to be an empty group (which looks like that was your problem). 

Have also reduced the number of records that are created, which means it won't take as long to run.

Try and give that another few goes after you update your local repository.

Failing that, am happy to troubleshoot with you if you would like to reach out to me on Slack (or where ever)
