### ISSUE TITLE
Slack + Zoom - Integration

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#93]
## Background

Create integrations between Slack, zoom and hackerspace.

## Questions

- [ ] What are these desired integrations?

**Comment by karwalski** [comment]
I am keen to assist here. Is this work in progress, and have requirements been written for this take?

**Comment by cassar** [comment]
Hey, that's great news @karwalski !

@karthikey-surineni and @npwilliams09 are you able to help Matt out?

**Comment by npwilliams09** [comment]
Hi @karwalski, Can you send me (Nathan Williams) a message on the govhack hq slack and we'll add you to the dev channel for this. Can go over more details there. Would love any help.

**Comment by karwalski** [comment]
Proposed pseudocode for the slack integration. App is installed and tested on the GovHack HQ.

`1# Add a button to profile page
    <a href="https://slack.com/oauth/v2/authorize?user_scope=identity.basic&client_id=7016354066.1274531651394&team=T070GAE1Y&state=CanBeUniqueString">Link to Slack</a>
    
2# Create a landing page for the user to be redirected back to from slack
    2.1 (optional) verify state string matches, else display error
    2.2a If error parameter returned or not HTTP 200, display error, OR
    2.2b If 'code' parameter (GET URL parameter) returned add to end of server side GET request (No headers needed) to https://slack.com/api/oauth.v2.access?client_id=7016354066.1274531651394&client_secret=GETSECRETFROMMATT&code=
    2.3 parse JSON response store authed_user.id as slack user in user table. Temp store authed_user.access_token (used in header below)
    2.4 Server side POST to https://slack.com/api/users.profile.set with below header and body

--Headers
Host: slack.com
Authorization: Bearer authed_user.access_token
Content-type: application/json; charset=utf-8

--Body
    {
        "profile": {
            "display_name": "Matt - GovHack Organiser",
            "title": "GovHack Organiser",
            "status_text": "Organiser",
            "status_emoji": ":govhack:"
        }
    }

Note. the body will be data from the hackers profile - to be determined by others`
