### ISSUE TITLE
Badges as the Award and Sneaky Reporting System

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#95]
## Background

The ability to give, receive and display badges on Hackerspace individual profiles and have team member earned badges displayed on their corresponding team profiles. Badges earned can be used to track participant engagement.

## Tasks

- Permisions: Organisers

**Comment by thesummerbard** [comment]
Note, requirements have been updated so that badges are awarded on an individual basis. Badges will be displayed on individual profiles. Team profiles will also display all badges earned by members of the team to encourage teams to work together to collect them all.
