### ISSUE TITLE
Add Mini Conference Event Type

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#96]
## Background

Will be happening around the same time as connections.

## Tasks

- [x] Add Mini Conference Event Type 
- [x] Update views
- [ ] Drop the 'Mini'

**Comment by cassar** [comment]
@Cruion, Mini Conference event type added.

They will appear as "Future" and "Past" sections on the Events index.

Can give them their own dedicated section like the other event types but would need a description.

You might want to consider revising the text in `app/views/competition_events/_competition_event_description.html.haml` also

**Comment by cassar** [comment]
@

**Comment by thesummerbard** [comment]
Let's call this 'GovHack 2020 Conference'
